services:
  exportservice:
    image: registry.eatx.pk/online-order-taking/exportservice:latest
    environment:
      - CONNECTIONSTRINGS__SQLSERVER=${MSSQLCONNECTION}
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  generalseodataservice:
    image: registry.eatx.pk/online-order-taking/generalseodataservice:latest
    environment:
      - KESTREL__ENDPOINTS__GRPC__URL=http://generalseodataservice:${GRPC_PORT}
      - KESTREL__ENDPOINTS__GRPC__PROTOCOLS=Http2
      - KESTREL__ENDPOINTS__HTTP__URL=http://generalseodataservice:${HTTP_PORT}
      - KESTREL__ENDPOINTS__HTTP__PROTOCOLS=Http1
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
    networks:
      - patroni-net

  pushnotificationservice:
    image: registry.eatx.pk/online-order-taking/pushnotificationservice:latest
    ports:
      - "8080"
    environment:
      - KESTREL__ENDPOINTS__GRPC__URL=http://pushnotificationservice:${GRPC_PORT}
      - KESTREL__ENDPOINTS__GRPC__PROTOCOLS=Http2
      - KESTREL__ENDPOINTS__HTTP__URL=http://pushnotificationservice:${HTTP_PORT}
      - KESTREL__ENDPOINTS__HTTP__PROTOCOLS=Http1
      - REDIS__CONNECTIONSTRING=${REDIS_HOST}:${REDIS_PORT},password=${REDIS_PASSWORD},abortConnect=false
      - VAPID__SUBJECT=${VAPID_SUBJECT}
      - VAPID__PUBLICKEY=${VAPID_PUBLIC_KEY}
      - VAPID__PRIVATEKEY=${VAPID_PRIVATE_KEY}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  customerorderhistoryservice:
    image: registry.eatx.pk/online-order-taking/customerorderhistoryservice:latest
    environment:
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  menuservice:
    build:
      context: .
      dockerfile: ./MenuService/Dockerfile
    environment:
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  orderhistoryservice:
    build:
      context: .
      dockerfile: ./OrderHistoryService/Dockerfile
    ports:
      - "8080"
    environment:
      - KESTREL__ENDPOINTS__GRPC__URL=http://orderhistoryservice:${GRPC_PORT}
      - KESTREL__ENDPOINTS__GRPC__PROTOCOLS=Http2
      - KESTREL__ENDPOINTS__HTTP__URL=http://orderhistoryservice:${HTTP_PORT}
      - KESTREL__ENDPOINTS__HTTP__PROTOCOLS=Http1
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  settingsdataservice:
    build:
      context: .
      dockerfile: ./SettingsDataService/Dockerfile
    environment:
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  clientnotifyservice:
    build:
      context: .
      dockerfile: ./ClientNotificationService/Dockerfile
    environment:
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  orderupdateservice:
    build:
      context: .
      dockerfile: ./OrderUpdateService/Dockerfile
    environment:
      - CONNECTIONSTRINGS__POSTGRES=${ROSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  importservice:
    build:
      context: .
      dockerfile: ./ImportService/Dockerfile
    environment:
      - CONNECTIONSTRINGS__SQLSERVER=${MSSQLCONNECTION}
      - CONNECTIONSTRINGS__POSTGRES=${RWSQLCONNECTION}
    networks:
      - patroni-net

  createorderservice:
    build:
      context: .
      dockerfile: ./CreateOrderService/Dockerfile
    environment:
      - KESTREL__ENDPOINTS__GRPC__URL=http://createorderservice:${GRPC_PORT}
      - KESTREL__ENDPOINTS__GRPC__PROTOCOLS=Http2
      - KESTREL__ENDPOINTS__HTTP__URL=http://createorderservice:${HTTP_PORT}
      - KESTREL__ENDPOINTS__HTTP__PROTOCOLS=Http1
      - CONNECTIONSTRINGS__POSTGRES=${RWSQLCONNECTION}
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
    networks:
      - patroni-net

  gatewayservice:
    build:
      context: .
      dockerfile: ./GatewayService/Dockerfile
    ports:
      - "8090:8080"
    environment:
      - GRPC__PUSHNOTIFICAIONHOST=http://pushnotificationservice:${GRPC_PORT}
      - GRPC__ORDERHISTORYHOST=http://orderhistoryservice:${GRPC_PORT}
      - GRPC__GENERALSEODATAHOST=http://generalseodataservice:${GRPC_PORT}
      - GRPC__CREATEORDERHOST=http://createorderservice:${GRPC_PORT}
      - ASPNETCORE_ENVIRONMENT=${GATEWAY_ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${GATEWAY_ASPNETCORE_URLS}
      - REDIS__CONNECTIONSTRING=${REDIS_HOST}:${REDIS_PORT},password=${REDIS_PASSWORD},abortConnect=false
      - RABBITMQ__HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ__PORT=${RABBITMQ_PORT}
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - JWT__KEY=${GATEWAY_JWT_KEY}
      - JWT__ISSUER=${GATEWAY_JWT_ISSUER}
      - JWT__AUDIENCE=${GATEWAY_JWT_AUDIENCE}
      - JWT__EXPIREMINUTES=${GATEWAY_JWT_EXPIREMINUTES}
    networks:
      - patroni-net

networks:
  patroni-net:
    driver: bridge
    name: patroni-net