<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PointofSaleModels\PointofSaleModels.csproj" />
    <Protobuf Include="Protos\pushnotification.proto" GrpcServices="Client" Namespace="PointofSaleModels.Protos" />
    <Protobuf Include="Protos\orderhistory.proto" GrpcServices="Client" Namespace="PointofSaleModels.Protos" />
    <Protobuf Include="Protos\generalseo.proto" GrpcServices="Client" Namespace="PointofSaleModels.Protos" />
  </ItemGroup>

</Project>
