syntax = "proto3";

option csharp_namespace = "PointofSaleModels.Protos";

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";

message Customer {
  int32 phone_id = 1;
  string name = 2;
  string contact = 3;
  string selected_address = 4;
  repeated string addresses = 5;
}

message CustomerDetail {
  string title = 1;
  string full_name = 2;
  string mobile_number = 3;
  string alternate_mobile_number = 4;
  string delivery_address = 5;
  string nearest_landmark = 6;
  string email_address = 7;
  string delivery_instructions = 8;
  string payment_method = 9;
  bool is_gift = 10;
  string recipient_name = 11;
  string recipient_number = 12;
  string gifting_message = 13;
}

message CustomerOrder {
  CustomerOrderContext customer_order_context = 1;
  string domain = 2;
  int32 branch_id = 3;
  string branch_name = 4;
  CustomerDetail customer_details = 5;
  string order_number = 6;
  string order_token = 7;
  string order_type = 8;
  string payment_type = 9;
  optional PaymentStatus payment_status = 10;
  string status = 11;
  double amount_with_gst = 12;
  double amount_without_gst = 13;
  repeated MenuItem items = 14;
  google.protobuf.Any order_status_logs = 15;
}

message CustomerOrderContext {
  User user = 1;
  google.protobuf.Timestamp order_time = 2;
  Rider rider = 3;
  Customer customer = 4;
  Discount discount = 5;
  string description = 6;
  optional int32 delivery_charges = 7;
  optional int32 delivery_time = 8;
}

message Discount {
  int32 id = 1;
  string type = 2;
  string name = 3;
  double value = 4;
  double max_cap = 5;
  double min_cap = 6;
}

message ItemChoice {
  int32 id = 1;
  string name = 2;
  int32 quantity = 3;
  int32 max_choice = 4;
  repeated ItemOption item_options = 5;
}

message ItemFlavour {
  int32 id = 1;
  string name = 2;
}

message ItemOption {
  int32 id = 1;
  string name = 2;
  double price = 3;
  optional int32 quantity = 4;
}

message ItemSize {
  int32 id = 1;
  string name = 2;
}

message ItemVariation {
  int32 id = 1;
  ItemSize size = 2;
  ItemFlavour flavour = 3;
  double price = 4;
  Discount discount = 5;
  repeated ItemChoice item_choices = 6;
}

message MenuItem {
  int32 id = 1;
  string category_id = 2;
  string code = 3;
  string name = 4;
  string department_name = 5;
  double price = 6;
  double tax_amount = 7;
  double quantity = 8;
  string image = 9;
  string comment = 10;
  bool is_kot = 11;
  bool item_foc = 12;
  string description = 13;
  repeated ItemVariation variations = 14;
  Discount discount = 15;
}

message Rider {
  int32 id = 1;
  string name = 2;
  string contact = 3;
}

message User {
  int32 id = 1;
  string name = 2;
  string username = 3;
  string password = 4;
  string token = 5;
  string terminal_uid = 6;
  repeated string pos_actions = 7;
}

enum PaymentStatus {
  PAYMENT_STATUS_UNDEFINED = 0;
  PAYMENT_STATUS_PENDING = 1;
  PAYMENT_STATUS_PAID = 2;
  PAYMENT_STATUS_REFUNDED = 3;
}
