syntax = "proto3";

option csharp_namespace = "OrderStatusService.GRPC";

package orderstatus;

message CustomerOrder {
  string domain = 1;
  int32 branch_id = 2;
  CustomerDetail customer_details = 3;
  string order_number = 4;
  OrderType order_type = 5;
  PaymentType payment_type = 6;
  PaymentStatus payment_status = 7;
  OrderStatus status = 8;
  repeated MenuItem items = 9;
}

message CustomerDetail {
  string title = 1;
  string full_name = 2;
  string mobile_number = 3;
  string alternate_mobile_number = 4;
  string delivery_address = 5;
  string nearest_landmark = 6;
  string email_address = 7;
  string delivery_instructions = 8;
  string payment_method = 9;
  bool is_gift = 10;
  string recipient_name = 11;
  string recipient_number = 12;
  string gifting_message = 13;
}

message MenuItem {
  int32 id = 1;
  string category_id = 2;
  string code = 3;
  string name = 4;
  string department_name = 5;
  double price = 6;
  double tax_amount = 7;
  double quantity = 8;
  string image = 9;
  string comment = 10;
  bool is_kot = 11;
  bool item_foc = 12;
  string description = 13;
  repeated ItemVariation variations = 14;
  Discount discount = 15;
}

message ItemVariation {
  int32 id = 1;
  ItemSize size = 2;
  ItemFlavour flavour = 3;
  double price = 4;
  Discount discount = 5;
  repeated ItemChoice item_choices = 6;
}

message ItemChoice {
  int32 id = 1;
  string name = 2;
  int32 quantity = 3;
  int32 max_choice = 4;
  repeated ItemOption item_options = 5;
}

message ItemOption {
  int32 id = 1;
  string name = 2;
  double price = 3;
}

message ItemSize {
  int32 id = 1;
  string name = 2;
}

message ItemFlavour {
  int32 id = 1;
  string name = 2;
}

message Discount {
  int32 id = 1;
  string type = 2;
  string name = 3;
  double value = 4;
  double max_cap = 5;
  double min_cap = 6;
}

enum PaymentType {
  PAYMENT_TYPE_UNDEFINED = 0;
  PAYMENT_TYPE_CASH = 1;
  PAYMENT_TYPE_CARD = 2;
  PAYMENT_TYPE_CREDIT = 3;
  PAYMENT_TYPE_VOUCHER = 4;
  PAYMENT_TYPE_FREEOF_COST = 5;
}

enum PaymentStatus {
  PAYMENT_STATUS_UNDEFINED = 0;
  PAYMENT_STATUS_PENDING = 1;
  PAYMENT_STATUS_PAID = 2;
  PAYMENT_STATUS_REFUNDED = 3;
}

enum OrderStatus {
  ORDER_STATUS_UNDEFINED = 0;
  ORDER_STATUS_PENDING = 1;
  ORDER_STATUS_PREPARING = 2;
  ORDER_STATUS_READY = 3;
  ORDER_STATUS_SERVED = 4;
  ORDER_STATUS_IN_TRANSIT = 5;
  ORDER_STATUS_DELIVERED = 6;
  ORDER_STATUS_CANCELLED = 7;
  ORDER_STATUS_CONFIRMED = 8;
  ORDER_STATUS_DISPATCH = 9;
  ORDER_STATUS_PAID = 10;
  ORDER_STATUS_ON_HOLD = 11;
}

enum OrderType {
  ORDER_TYPE_UNDEFINED = 0;
  ORDER_TYPE_DINE_IN_INDOOR = 1;
  ORDER_TYPE_DINE_IN_OUTDOOR = 2;
  ORDER_TYPE_TAKE_AWAY = 3;
  ORDER_TYPE_DELIVERY = 4;
}
