name: All Services Deployment

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment (production or development)"
        required: true
        type: string

jobs:
  build-services:
    name: Build services in parallel for ${{ inputs.environment }}
    if: github.event.inputs.service == 'all' || github.event_name == 'push'
    strategy:
      max-parallel: 4
      matrix:
        service:
          - exportservice
          - generalseodataservice
          - pushnotificationservice
          - customerorderhistoryservice
          - menuservice
          - orderhistoryservice
          - settingsdataservice
          - clientnotifyservice
          - orderupdateservice
          - importservice
          - createorderservice
          - gatewayservice

    uses: ./.github/workflows/build-image.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ matrix.service }}
    secrets: inherit

  deploy-services:
    name: Deploy services in parallel to ${{ inputs.environment }}
    needs: build-services
    if: github.event.inputs.service == 'all' || github.event_name == 'push'
    strategy:
      max-parallel: 4
      matrix:
        service:
          - exportservice
          - generalseodataservice
          - pushnotificationservice
          - customerorderhistoryservice
          - menuservice
          - orderhistoryservice
          - settingsdataservice
          - clientnotifyservice
          - orderupdateservice
          - importservice
          - createorderservice
          - gatewayservice

    uses: ./.github/workflows/deploy-image.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ matrix.service }}
    secrets: inherit
