name: Single Service Deployment

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment (production or development)"
        required: true
        type: string
      service:
        description: "Service to deploy"
        required: true
        type: string

jobs:
  build-service:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ inputs.service }}
    secrets: inherit

  deploy-service:
    uses: ./.github/workflows/deploy-image.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ inputs.service }}
    secrets: inherit
