name: Staging Deployment

on:
  pull_request:
    types: [closed]
    branches: [staging, private_registry_setup]
  workflow_dispatch:
    inputs:
      service:
        description: "Service to deploy (or all)"
        required: false
        type: choice
        default: "all"
        options:
          - all
          - exportservice
          - generalseodataservice
          - pushnotificationservice
          - customerorderhistoryservice
          - menuservice
          - orderhistoryservice
          - settingsdataservice
          - clientnotifyservice
          - orderupdateservice
          - importservice
          - createorderservice
          - gatewayservice
          - website
          - backpanel
          - infrastructure

jobs:
  infrastructure:
    if: github.event.inputs.service == 'infrastructure'
    uses: ./.github/workflows/infrastructure-deployment.yml
    with:
      environment: development
    secrets: inherit

  deploy-all-services:
    if: github.event.inputs.service == 'all'
    uses: ./.github/workflows/all-services-deployment.yml
    with:
      environment: development
    secrets: inherit

  deploy-website:
    if: github.event.inputs.service == 'website'
    uses: ./.github/workflows/website-deployment.yml
    with:
      environment: development
    secrets: inherit

  deploy-backpanel:
    if: github.event.inputs.service == 'backpanel'
    uses: ./.github/workflows/backpanel-deployment.yml
    with:
      environment: development
    secrets: inherit

  single-service-deployment:
    if: contains(github.event.inputs.service, 'service')
    uses: ./.github/workflows/single-service-deployment.yml
    with:
      service: ${{ github.event.inputs.service }}
      environment: development
    secrets: inherit
