name: Website Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  website:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: github.event.inputs.service == 'all' || github.event.inputs.service ==
      'website'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Checking if website directory exists on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            if [ -d "OnlineOrderTaking/nextjs/web-ordering" ]; then
              echo Website directory exists on VPS
            else
              echo Website directory does not exist on VPS && exit 1
            fi

      - name: Transfer Docker for website
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "nextjs/Dockerfile"
          target: "/home/${{ secrets.VPS_USERNAME }}/OnlineOrderTaking/nextjs/"
          timeout: "30s"
          command_timeout: "10m"

      - name: Deploy website
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/OnlineOrderTaking/nextjs/web-ordering
            git pull && cd ..
            # Build and restart website
            docker compose stop website 2>/dev/null || true
            docker rm website 2>/dev/null || true
            docker compose build website --no-cache
            docker compose up -d website
